apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallpaper-app
  labels:
    app: wallpaper-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallpaper-app
  template:
    metadata:
      labels:
        app: wallpaper-app
    spec:
      containers:
      - name: wallpaper-app
        image: mudipa/wallpaper-app:latest
        ports:
        - containerPort: 80
